spring:
  application:
    name: microservice-consumer-movie-ribbon
server:
  port: 10005
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true