server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:wangziyangzk/springcloud
          username:
          password:

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:10001/eureka
  instance:
    prefer-ip-address: true